import Head from 'next/head';
// import Image from 'next/image';
// import { Inter } from 'next/font/google';
import styles from '@/styles/Home.module.css';
import Card from '@/components/card/card';
import DollarCard from '@/components/card/dollarCard/dollarCard';
import HollidayCard from '@/components/card/hollidayCard/hollidayCard';

// const inter = Inter({ subsets: ['latin'] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Infohub</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <Card
          data={{
            title: 'Dólar Blue',
            footer: 'Actualizado el 19/04/23 07:01 PM',
          }}
        >
          <DollarCard value="$423" />
        </Card>
        <Card
          data={{
            title: 'Próximo Feriado',
            footer: 'Actualizado el 19/04/23 07:01 PM',
          }}
        >
          <HollidayCard
            day="1Mayo"
            reason="Feriado Día del Trabajador"
            remaining="Faltan 11 días"
          />
        </Card>
      </main>
    </>
  );
}
