import Head from 'next/head';
import styles from '@/styles/Home.module.css';
import Card from '@/components/card/card';
import DollarCard from '@/components/card/dollarCard/dollarCard';
import HollidayCard from '@/components/card/hollidayCard/hollidayCard';
import Header from '@/components/header/header';
import { useEffect, useState } from 'react';

type DollarData = {
  value: string;
};

type HollidayData = {
  day: string;
  left: string;
  reason: string;
};

type CardData = {
  id: number;
  title: string;
  footer: string;
};

interface DollarCardData extends CardData {
  data: DollarData;
}

interface HolidayCardData extends CardData {
  data: HollidayData;
}

const Home = () => {
  const [dollarCard, setDollarCard] = useState<DollarCardData>({
    id: 0,
    data: { value: '' },
    footer: '',
    title: '',
  });
  const [holiDayCard, setHoliDayCard] = useState<HolidayCardData>({
    id: 0,
    data: { day: '', reason: '', left: '' },
    footer: '',
    title: '',
  });

  useEffect(() => {
    const intervalId = setInterval(() => {
      fetchDollarData();
    }, 1000 * 5);
    return () => clearInterval(intervalId);
  }, []);

  useEffect(() => {
    fetchHolidayData();
    // const intervalId = setInterval(() => {
    // }, 1000 * 5);
    // return () => clearInterval(intervalId);
  }, []);

  const fetchDollarData = async () => {
    const dollarResp = await fetch('/api/dollar');
    const dollarData = await dollarResp.json();

    setDollarCard(dollarData);
  };

  const fetchHolidayData = async () => {
    const holidayResp = await fetch('/api/holiday');
    const holidayData = await holidayResp.json();

    setHoliDayCard(holidayData);
  };

  return (
    <>
      <Head>
        <title>Infohub</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <Header />
        <Card
          key={dollarCard.id}
          data={{
            title: dollarCard.title,
            footer: dollarCard.footer,
          }}
          refresh={fetchDollarData}
        >
          {dollarCard.title === '' ? (
            <div className={styles.loading}>Cargando...</div>
          ) : (
            <DollarCard value={dollarCard.data.value} />
          )}
        </Card>
        <Card
          key={holiDayCard.id}
          data={{
            title: holiDayCard.title,
            footer: holiDayCard.footer,
          }}
          refresh={fetchHolidayData}
        >
          {holiDayCard.title === '' ? (
            <div className={styles.loading}>Cargando...</div>
          ) : (
            <HollidayCard
              day={holiDayCard.data.day}
              reason={holiDayCard.data.reason}
              left={holiDayCard.data.left}
            />
          )}
        </Card>
      </main>
    </>
  );
};

export default Home;
